### ISSUE TITLE
css class to mark a button of a button group as active?

### ISSUE THREAD

**Issue by clement911** [shoppad/UptownCSS#1]
I see a css rule for &active but shouldn't there be a similar rule for .active?
Or is the idea that it should be marked as .primary once the user selects it?

**Comment by ryanodo** [comment]
@clement911 no, there isn't a .active class for buttons. The:active state gives buttons a "pressed" visual but is not meant to remain afterward.

What you're describing sounds more like tabs than buttons.

**Comment by clement911** [comment]
I see.
I guess I'm used to bootstrap where the button group can also be used as
fancy radio button.
