### ISSUE TITLE
Can't browse back and forth using Apple trackpad

### ISSUE THREAD

**Issue by Ennazk** [shoppad/UptownCSS#14]
Hello,

I can't go back to previous page with my Apple trackpad.

For example, a MacBook user is used to go back to the previous by swiping two fingers horizontally on the trackpad.

This functionality is disabled when using UptownCSS.

I'm on Chrome 63

Is this done on purpose?

Thanks.

**Comment by ryanodo** [comment]
Can you give me steps to reproduce this so I can investigate this for you?

Thanks

**Comment by Ennazk** [comment]
Here is a video. UptownCSS vs Laravel Doc: https://youtu.be/BY_NDZrCYHE

Here is the gesture used: http://bit.ly/2mNZeIL

Thank you.

**Comment by ryanodo** [comment]
There's nothing on the site designed to disable this ability. 

I can only reproduce this in instances when my swiping gesture is slower or less of a quick swiping motion which results in pulling the browser's canvas and the gesture not registering as a two-finger swipe.

There's also nothing in the CSS around disabling this if ever deplyed within a Shopify app.

**Comment by Ennazk** [comment]
Alright thank you. I'll close this and reopen if I find a solution related to this repo's code. Thanks for the awesome work Ryan.
